listenEndpoint: "0.0.0.0:9090"
staticRoutes:
  - resource: "pve10"
    target: "192.168.1.40"
  - resource: "altK8s"
    target: "192.168.1.216"
  - resource: "nix"
    target: "192.168.1.206" #questionable
kubernetesControlEndp: "junk"
ecdsaKey: "./server_id_ed25519" 
